# Generated by Django 3.2.10 on 2024-04-23 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='部门id')),
                ('title', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_time', models.DateField()),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')])),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.department')),
            ],
        ),
    ]
