# Generated by Django 3.2.10 on 2024-04-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_auto_20240428_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '普通')], default=1, verbose_name='级别')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详情')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.userinfo')),
            ],
        ),
    ]
